### ISSUE TITLE
Text cut off on mobile 

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/good-first-issue-finder#100]
### Description

Too much text is cut off from each issue on mobile (screenshot from iPhone XS) especially when there is also a label. Suggestion: text should wrap onto next line instead of be cut off. 

### Screenshots

![72B2D91E-99D2-44AE-8BD1-D8747CCC075F](https://user-images.githubusercontent.com/57045550/156216848-4c416c21-b6e4-4dff-9ba3-49788a98d7c8.png)

**Comment by KendallDoesCoding** [comment]
> ### Description
> Too much text is cut off from each issue on mobile (screenshot from iPhone XS) especially when there is also a label. Suggestion: text should wrap onto next line instead of be cut off.
> 
> ### Screenshots
> ![72B2D91E-99D2-44AE-8BD1-D8747CCC075F](https://user-images.githubusercontent.com/57045550/156216848-4c416c21-b6e4-4dff-9ba3-49788a98d7c8.png)
> 
> ### Additional information
> _No response_

I can try to work on this.
