### ISSUE TITLE
Missing title tag in head

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/good-first-issue-finder#101]
### Description

Add <title> tag to the head section of the html.

**Comment by suhaasya** [comment]
I like to work on this issue. can anyone assign it to me ??

**Comment by suhaasya** [comment]
hey Emma can you help me to run an app in my local environment.  I don't know how to run the svelte app. I did fix the issue but I wanna check it before commit.

**Comment by emmalearnscode** [comment]
which commands did you run? It should be enough to run npm install followed by npm run dev --open

**Comment by suhaasya** [comment]
I had run
npm install then
npm run dev --open

now getting this issue.
![Uploading Screenshot (418).png…]()

**Comment by suhaasya** [comment]
I can run now. I was missing creating a .env file. 

I also had made a pull request.

one suggestion from my side. someone should create CONTRIBUTTING.md asap.

**Comment by emmalearnscode** [comment]
Glad you figured it out 👍🏻

**Comment by suhaasya** [comment]
my pr request got merged. you can close this issue now.

**Comment by emmalearnscode** [comment]
Pr #113
