### ISSUE TITLE
[OTHER] Use header tag instead of div tag

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/good-first-issue-finder#102]
### What would you like to share?

Use a header tag around the title, toggle and search bar instead of a div to improve the semantics of the site.

**Comment by emmalearnscode** [comment]
Sure, go ahead :)

**Comment by mdaquib171** [comment]
Is this issue is still pending, if it is then I would like to contribute to this 
As I am looking for first time to contribute to open source 
please help me out
thanks

**Comment by emmalearnscode** [comment]
@umeshthakre how’s it going? Are you still working on this or are you happy for @mdaquib171 to take over?

**Comment by Benmuiruri** [comment]
Hello everyone, it looks like it's been a while since an update on this issue was given. If it is still open, I would like to work on it

**Comment by emmalearnscode** [comment]
Ok, I unassigned @umeshthakre, please feel free to go ahead and work on it.

**Comment by Benmuiruri** [comment]
Thanks Emma, I will give it a shot.

**Comment by Benmuiruri** [comment]
Hi @emmalearnscode, I inspected the page and it seems to me that the content is already wrapped by a `header` tag. 

See the image below, Let me know if this issue still needs to be handled. 
![header-fix](https://user-images.githubusercontent.com/2597305/168250764-f1b7c729-dc8d-496e-85bb-7fa104563d91.png)

**Comment by Benmuiruri** [comment]
Okay, I will do that.

**Comment by gandhiv88** [comment]
Hi @emmalearnscode, Is this issue still open? Please let me know.

**Comment by Benmuiruri** [comment]
Hi Gandhi, thanks for reminding me. Let me push the requested change

**Comment by Benmuiruri** [comment]
Hello @emmalearnscode I made the change, I have tried to push but I have received this error `Please make sure you have the correct access rights` How do I go about pushing the changes? 

Thanks

**Comment by emmalearnscode** [comment]
Sorry for the late reply, did you work it out or do you still need help?

**Comment by Benmuiruri** [comment]
Hi @emmalearnscode  I did not. What do I need to do to get the rights?

**Comment by Cahllagerfeld** [comment]
Did you create a fork before trying to commit or push your changes? You should push to your fork and then open the PR to the upstream

**Comment by Benmuiruri** [comment]
@Cahllagerfeld I cloned the repo, I did not fork it. I will form it instead.

**Comment by Dhruv-Gajjar** [comment]
Hey @emmalearnscode can i know if i can work on this issue?
