### ISSUE TITLE
Clicking x does not reset search

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/good-first-issue-finder#106]
### Description

On Chrome browser when searching a small cross appears next to the word. When it is clicked the word disappears but the search does not get reset so it continues to show only the issues which match the search.

to do: When the x is clicked the search term should reset to "" and all items should be shown again.

**Comment by KendallDoesCoding** [comment]
> ### Description
> On Chrome browser when searching a small cross appears next to the word. When it is clicked the word disappears but the search does not get reset so it continues to show only the issues which match the search.
> 
> to do: When the x is clicked the search term should reset to "" and all items should be shown again.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Yup, it's clearing it up from the bar, but it's not reseting the items.

**Comment by Mishra121** [comment]
@emmalearnscode , @KendallDoesCoding  
I guess better approach to handle this UI scenario will be:
1. to  remove the default cross added by chrome in the type=search input
2. create a custom cross feature to work across different browsers.
