### ISSUE TITLE
[OTHER] How do I get my profile on Global?

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#107]
### What would you like to share?

Rn, I can only see Krish and Eddie's profile on the global menu, how do I set it up for my repos too?

**Comment by emmalearnscode** [comment]
You add the Eddiehub:good-first-issue label to any issues in your respos that you think are suitable for beginners and that have sufficient explanation for how to succeed.

**Comment by KendallDoesCoding** [comment]
> You add the Eddiehub:good-first-issue label to any issues in your respos that you think are suitable for beginners and that have sufficient explanation for how to succeed.

And then it will automatically add here?

**Comment by emmalearnscode** [comment]
It should do, that's what they were testing on the stream yesterday. Try it out and see if it appears (you will have to select global instead of organization)

**Comment by KendallDoesCoding** [comment]
> It should do, that's what they were testing on the stream yesterday. Try it out and see if it appears (you will have to select global instead of organization)

Yup, it does appear, pretty cool... Closing
