### ISSUE TITLE
[DOCS] Open in gitpod icon in README.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#108]
### Description

Add a open in gitpod icon in README that if tapped will open this project in Gitpod.

**Comment by suhaasya** [comment]
I would like to do this task. can anyone assign me??

**Comment by Shivansh-yadav13** [comment]
I think this issue can be closed now.

**Comment by aroramrinaal** [comment]
> I think this issue can be closed now.

Yes this issue can be closed now.
