### ISSUE TITLE
Issue with filtering language

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#109]
### Description

A Code of Conduct is .md script, if I am not mistaken, in the good-issue-finder, it's filtering under CSS

### Screenshots

![image](https://user-images.githubusercontent.com/84712013/156227936-1f862bcb-7f27-48e8-ae37-070b47e60064.png)

**Comment by KendallDoesCoding** [comment]
Same issue with this.


![image](https://user-images.githubusercontent.com/84712013/156228087-a7ef3241-d05f-46a3-86a2-c4e119900dfa.png)

**Comment by emmalearnscode** [comment]
It's showing the main language of the entire repo, the one that can be seen in the right hand panel under the about section on each repo, not the language of the specific file to be edited.
