### ISSUE TITLE
[FEATURE] Not case sensitive label to be added in Global

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#110]
### Description

rn the label as to be: EddieHub:good-first-issue, I made the h in Hub, lowercase and it didn't show up, I think it will be better if it shows up, regardless of the case, even if the full label is in lowercase?

**Comment by KendallDoesCoding** [comment]
Idk if it already is has for the same issue seem to be facing another issue #111

**Comment by Cahllagerfeld** [comment]
At least in my opinion it's fine how it currently is. I wouldn't want to highjack too many possible labels. I think documenting properly, which Label needs to be added should be enough. What do you think about it @emmalearnscode @schmelto

**Comment by schmelto** [comment]
Agree with that @Cahllagerfeld

**Comment by Cahllagerfeld** [comment]
closing this for now, see relevant discussion above
