### ISSUE TITLE
Issue not showing up in global

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#111]
### Description

I added a issue 14 minutes back with the label, but it's still not showing up under Global, my other issue, showed up there within 2 mins.

**Comment by emmalearnscode** [comment]
If you spelt it correctly then this is most probably because the github API only updates every 15-20 minutes. This was a big worry point during hacktoberfest when everyone wondered why their pull requests didn't track immediately. I bet if you give it a few minutes it will appear.

**Comment by KendallDoesCodingAlt1** [comment]
Well, the other issue showed up... Out of the 3 issues put the label, only one showed up though?

**Comment by KendallDoesCodingAlt1** [comment]
It's coz I had someone assigned to the issue, after removed it it's showing up. Please close this issue.

**Comment by eddiejaoude** [comment]
> It's coz I had someone assigned to the issue, after removed it it's showing up. Please close this issue.

Thank you for letting us know. Sure I can close this.
