### ISSUE TITLE
[DOCS] Modify 3rd line from the installation steps

### ISSUE THREAD

**Issue by suhaasya** [EddieHubCommunity/good-first-issue-finder#119]
### Description

When we clone the good-first-issue-finder repository.
good-first-issue-finder directory will created in system.

So third line should be cd good-first-issue-finder instead of cd linkfree.

### Screenshots

![Screenshot (433)](https://user-images.githubusercontent.com/75799016/161397855-2dc53c50-271b-4feb-b7cd-007761087a27.png)

**Comment by The-Shivam-garg** [comment]
Hye @suhaasya would love to work on this issue , can you please assign this issue to me .

**Comment by schmelto** [comment]
I think we could leave this line but clarify it a little bit more. After cloning you have to go into your cloned folder in this case linkfree in this perspective the step makes sense to me. But you are also right there is no linkfree folder in linkfree :D

**Comment by suhaasya** [comment]
We can't leave this line. Because it will confuse developers.
It's good-first-issue-finder project not linkfree.
Contributor just copy paste lines from linkfree readme.

I have to change the issue title.
It should be modify the third link
From CD linkfree to cd good-first-issue-finder.

**Comment by schmelto** [comment]
> We can't leave this line. Because it will confuse developers.
> 
> It's good-first-issue-finder project not linkfree.
> 
> Contributor just copy paste lines from linkfree readme.
> 
> 
> 
> I have to change the issue title.
> 
> It should be modify the third link
> 
> From CD linkfree to cd good-first-issue-finder.

Ups hahaha yeah wrong repo 😅😅😅 you are right

**Comment by suhaasya** [comment]
hey @The-Shivam-garg,
I am not able to see any option to assign the issue. 
i think this option is only available for maintainers.

**Comment by emmalearnscode** [comment]
@The-Shivam-garg I assigned you. Let us know if you need help with anything.

**Comment by schmelto** [comment]
@The-Shivam-garg still working on this issue?

**Comment by The-Shivam-garg** [comment]
modified the changes as suggested ,please check it out the **PR  #124** and if there is any further changes required please do acknowledge me with that.

**Comment by emmalearnscode** [comment]
Closed by PR #124
