### ISSUE TITLE
[DOCS] Make installation step 5 clearer

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/good-first-issue-finder#127]
### Description

At the moment instruction 5 says: Add a GitHub Token in .env (Copy .env.example and paste credentials)

It would be clearer is it instead says: Create a .env file in the root of the project. Then add your GitHub token (see example in .env.example file)

**Comment by frazie** [comment]
This only needs an edit on the readme text, right?

**Comment by emmalearnscode** [comment]
@frazie Yes, that's right

**Comment by frazie** [comment]
I can handle that
kindly assign it to me
