### ISSUE TITLE
[OTHER] Does this site actually need a nav component?

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/good-first-issue-finder#145]
### What would you like to share?

Since there is currently only one page and the nav component links back to itself, this could be confusing for screen reader users.

I suggest we remove the nav component and the Hubber icon can just be a part of the header and not be a link unless it is intended to add more pages.

**Comment by Jyotiraditya24** [comment]
hey I can resolve this issue?

**Comment by Dharmik48** [comment]
Do you think something like this will work?
![new design idea](https://user-images.githubusercontent.com/64529217/176898339-c0236b8d-1a9a-4a07-9b10-be2283ecb1e3.png)

**Comment by Cahllagerfeld** [comment]
I like the idea 👍

**Comment by Dharmik48** [comment]
> I like the idea 👍 

Great, I'll get to work then

**Comment by Dharmik48** [comment]
Hey @Cahllagerfeld now that I am finished with this issue, can I work on #82 ?
