### ISSUE TITLE
Change the Hubber icon in the nav bar

### ISSUE THREAD

**Issue by Dharmik48** [EddieHubCommunity/good-first-issue-finder#164]
### Description

We changed the favicon of the website to one of the Hubbers from the branding repo, but the Hubber in the header of the website is different from the one in the favicon.

So I think to be consistent, we should change the Hubber in the header to be the same as in the favicon.

### Screenshots

The one in the favicon: 
![favicon hubber](https://user-images.githubusercontent.com/64529217/176891556-1ff7890b-7910-4b19-9875-5a5acea957cc.png)

The one in the header:
![header hubber](https://user-images.githubusercontent.com/64529217/176891393-9739ddcf-fb7e-402d-bbf5-d278f6052e6e.png)

### Additional information

I am up to solve this issue

**Comment by Cahllagerfeld** [comment]
Affected by #145

**Comment by Dharmik48** [comment]
I can try to solve #145

**Comment by Dharmik48** [comment]
Hey @Cahllagerfeld I have a proposed a new header design in the #145 comments, please give your reviews on that.

**Comment by ianujvarshney** [comment]
i can resolve this issue i never get any badge please assign this issue.

**Comment by Cahllagerfeld** [comment]
I think its okay if @ianujvarshney works on that issue, as @Dharmik48 is working on #145. What do you think?

The only think we need to keep in mind, that we potentially run into merge conflicts, when doing this at the same time, but we got this I think 💪

**Comment by Dharmik48** [comment]
That's a good solution, that way we both get a chance to contribute to the project 😄

**Comment by Dharmik48** [comment]
Hey @ianujvarshney , as you will be working on this issue, you will find the png of Hubber in the [Branding](https://github.com/EddieHubCommunity/Branding) repo.

**Comment by Dharmik48** [comment]
> Hey @ianujvarshney , as you will be working on this issue, you will find the png of Hubber in the [Branding](https://github.com/EddieHubCommunity/Branding) repo.

Select the same Hubber as the favicon one

**Comment by ianujvarshney** [comment]
Sure i will do it. 👍

**Comment by Cahllagerfeld** [comment]
closed with #168
