### ISSUE TITLE
Clicking the 'X' to clear the search, does not reset the list

### ISSUE THREAD

**Issue by jameslieu** [EddieHubCommunity/good-first-issue-finder#169]
### Description

When clearing the search filter, as a user I would expect the list to also be restored to what it was prior to searching.

**Comment by Dharmik48** [comment]
This issue is similar to #106

**Comment by jameslieu** [comment]
No response or activity on this also, as mentioned, it is a duplicate of https://github.com/EddieHubCommunity/good-first-issue-finder/issues/106

I'll close this as well.
