### ISSUE TITLE
[OTHER] Is the Gear near theme toggle doing something?

### ISSUE THREAD

**Issue by vrindavan** [EddieHubCommunity/good-first-issue-finder#170]
### What would you like to share?

I tried inspecting but could not find if there is a use case for the Gear icon (screenshot attached). I think it might be redundant at the moment.
When using the Theme toggle, it works perfectly but the Gear icon seems to be doing nothing. Am I missing something? When you refresh the page the Gear is selected first and then one can switch the theme, but we can just mark the dark theme button active instead of Gear.

### Additional information

![image](https://user-images.githubusercontent.com/50140643/178114868-41ca1dc2-6f22-4e69-a1e5-90713fa1f1e6.png)

**Comment by Cahllagerfeld** [comment]
The Gear Setting picks up your system setting - e.g when your local theme changes from light to dark at a certain time, its going to be reflected in the application

**Comment by vrindavan** [comment]
So the Gear is basically for System Theme?
