### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by KarlGusta** [EddieHubCommunity/good-first-issue-finder#173]
### Description

- To change the repo description from Github to GitHub.

### Screenshots

![image](https://user-images.githubusercontent.com/33565767/182373183-da700d37-3467-42d9-92bc-ed5812cebbe6.png)

**Comment by kelvinparmar** [comment]
I would like to work on that issue @KarlGusta 
Please assign to me

**Comment by Cahllagerfeld** [comment]
I think, you don't have the required permissions to adjust these repo settings @kelvinparmar

**Comment by kelvinparmar** [comment]
Ohk @KarlGusta

**Comment by eddiejaoude** [comment]
I assigned it to @kelvinparmar 👍 

You should have permission @Cahllagerfeld 🤔 you were able to assign it to me? Let's chat in Discord and figure out why so we can solve it so you have more permissions

**Comment by kelvinparmar** [comment]
How can i change it because where the text is available?

**Comment by kelvinparmar** [comment]
Readme file not showing me

**Comment by eddiejaoude** [comment]
Sorry I just read the issue, you cannot change the repo description, only a project maintainer can, I will assign it back to me

**Comment by kelvinparmar** [comment]
Yeah because changes are not in readme file it's in discription

**Comment by kelvinparmar** [comment]
So now what i have to do?

**Comment by eddiejaoude** [comment]
Unfortunately you cannot not do this ticket, a PR cannot be raised for it. I have updated the description in the repo settings. I suggest looking at another issue. I have added the label `staff only`

Please do not just send 1 line comments a few seconds apart, it creates a lot of notifications for everyone, it is best to put them in a single comment

**Comment by kelvinparmar** [comment]
Ok @eddiejaoude I am understand it. Thank you
