### ISSUE TITLE
Improved Footer for Good First Issue Finder

### ISSUE THREAD

**Issue by jyotsnad246** [EddieHubCommunity/good-first-issue-finder#177]
### What would you like to share?

The footer can be improved 
Currently this is the footer
<img width="764" alt="image" src="https://user-images.githubusercontent.com/84655618/184025950-5d218c91-dcae-4d29-b17a-1c0c52ed4cb9.png">

**Comment by jasham** [comment]
Hello @jyotsnad246 can you please explain me how the expected footer will look like ?

**Comment by sanyamgandhak** [comment]
Hi , I will do this task . I will make the footer broader and icon larger . Please assign this to me

**Comment by Cahllagerfeld** [comment]
The footer got refactored already, so it currently doesn't look like the one on the screenshot anymore. Please see my comments in the PR #178 as well.

**Comment by Rajeevjewar** [comment]
I am working on it.

**Comment by Rajeevjewar** [comment]
> The footer got refactored already, so it currently doesn't look like the one on the screenshot anymore. Please see my comments in the PR #178 as well.

I think i am late to contribute to it.

**Comment by Pjha72** [comment]
I am working on it.

**Comment by nithin999989** [comment]
please assign this to me @eddiejaoude i would like to contribute this

**Comment by Vishal777956** [comment]
> 

please can you elaborate how you expect footer to be changed?

**Comment by eddiejaoude** [comment]
Thank you all for the collaboration. As this issue is still awaiting triage and has no clear goal of what the improvements should be. I will close this issue
