### ISSUE TITLE
Small Layout Shift

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#212]
### Description

There's a small layout shift when navigating away from the `/` route to `/docs` or `/login`

It's caused by the scrollbar. I'm not sure if there's a way to get around this thouhg

**Comment by sanyamgandhak** [comment]
Hi there , Please assign it to me

**Comment by Cahllagerfeld** [comment]
I can assign it to you, but I think there's no action item to do here. Based on my investigations, this small shift is caused by the scrollbar, which we can't get rid of on longer pages

**Comment by arjandhakal** [comment]
There is a CSS property called scrollbar-gutter. Maybe using it on the main container div or the body could fix the issue.

This is a very good [article](https://www.bram.us/2021/07/23/prevent-unwanted-layout-shifts-caused-by-scrollbars-with-the-scrollbar-gutter-css-property/) about it here.

**Comment by arun-kushwaha04** [comment]
Yep, experienced the same thing. The bottom scrollbar on `/` page is kind of annoying. I think that i can fix this issue. @Cahllagerfeld can you assign this to me.

**Comment by Cahllagerfeld** [comment]
I think this issues isn't up-to-date anymore. The issues was caused by the scrollbar on `/`, which now is `/app`.

Do you have a horizontal-scrollbar on some pages? :o I just tested it and can't reproduce it

**Comment by arun-kushwaha04** [comment]
Yes I have horizontal scrollbar on `/`, while its disappears on other pages.
### Horizontal scrollbar on `/` route
<img src="https://user-images.githubusercontent.com/73020364/218093611-55991b3a-b938-484b-af5c-f36645814801.png"  width="100%">

### No Horizontal scrollbar on `/docs` routes (desired same behavior on `/` route)
<img src="https://user-images.githubusercontent.com/73020364/218093616-56a2ade1-bce5-4071-ac1c-485172a1b6cc.png"  width="100%">
</div>

**Comment by arun-kushwaha04** [comment]
@Cahllagerfeld opened a PR to fix the bottom scrollbar issue on `/` route please check.
