### ISSUE TITLE
[FEATURE] Move Filters to Modal

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#215]
### Description

Currently the list of filters might become quite long + in addition when having additional filters, e.g the one for languages, the space this entire filter thing takes in might become very big. We should htink about moving the filter stuff to modals so they don't block the actual UI

**Comment by ChinmayMhatre** [comment]
I could give this a try!

**Comment by thevinitgupta** [comment]
I would like to work on this.

**Comment by rprav-n** [comment]
@Cahllagerfeld Can I work on this?

**Comment by Cahllagerfeld** [comment]
Yes 👍

**Comment by rprav-n** [comment]
@Cahllagerfeld 

This feature has been added in this MR: https://github.com/EddieHubCommunity/good-first-issue-finder/pull/319
