### ISSUE TITLE
[FEATURE] SEO Optimization

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#220]
### Description

Add Meta Information, Opengraph, etc...

This can be achieved by using the `<svelte:head>` tag, in `.svelte-files` in the `routes` directory

**Comment by flomero** [comment]
hey @Cahllagerfeld can I work on this issue if it has not been assigned yet?

**Comment by Cahllagerfeld** [comment]
Sure 👍 Let me update the description, and explain things more detailed

**Comment by Cahllagerfeld** [comment]
closed with #235
