### ISSUE TITLE
Add Hamburger Menu for mobile devices

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#227]
### Description

We're currently not differentiating between large screens and smaller devices. We should change the layout of the navbar if the breakpoint is below `lg`. An Hamburger Menu would be ideal for this.

**Comment by Ann-design-max** [comment]
Hi @Cahllagerfeld  Can I work on this issue if it has not been assigned?

**Comment by Cahllagerfeld** [comment]
Sure 👍🏽

**Comment by Ann-design-max** [comment]
Thanks @Cahllagerfeld . I need a little help though. I can't seem to login on local. Started a discussion on it here 
https://github.com/orgs/EddieHubCommunity/discussions/5454

**Comment by PrakritiShetty** [comment]
Hi, can I please work on this issue?

**Comment by arun-kushwaha04** [comment]
Hi @Cahllagerfeld can i work on this issue ??

**Comment by Cahllagerfeld** [comment]
Yes, I think you can, there hasn't been much activity for quite a while

**Comment by arun-kushwaha04** [comment]
@Cahllagerfeld i have created a pr for this issue, can you check it.

**Comment by alokVerma749** [comment]
this issue is resolved by #277, if there is other changes required then please mention

**Comment by Cahllagerfeld** [comment]
nice catch! It's done indeed 👍
