### ISSUE TITLE
[DOCS] <We should add "upgrade node version above  6.14.0 " >

### ISSUE THREAD

**Issue by Atharv181** [EddieHubCommunity/good-first-issue-finder#234]
### Description

After fork and cloning of project I ran command of npm install but it didn't work for me because my node version was 6.13.
We can add extra step after 3rd step of **Installation Steps** .

### Screenshots

![image](https://user-images.githubusercontent.com/73999654/193842017-34446b64-96c4-4bba-8c35-0b50b11b3656.png)

**Comment by Cahllagerfeld** [comment]
I think this is your local node version, and not related to the project
Can you please run `node -v` in your terminal

**Comment by Atharv181** [comment]
Yes I solved the problem but I thought if any beginner faced the same issue then he might not able to solve.

**Comment by Atharv181** [comment]
So do you want me to make pr or close the issue?

**Comment by Cahllagerfeld** [comment]
Nono, feel free to adjust documentation on this!

**Comment by Atharv181** [comment]
Ok then I will work on that.
