### ISSUE TITLE
[FEATURE] Filter out Assigned Issues

### ISSUE THREAD

**Issue by Akshu-on-github** [EddieHubCommunity/good-first-issue-finder#238]
### Description

Noticed a few issues turning up that had folks assigned to them because maintainers hadn't removed the `EddieHub:good-first-issue` label yet 

Perhaps we can filter out issues that have been assigned to contributors already?

### Screenshots

![Screenshot_2022-10-01-01-01-42-24](https://user-images.githubusercontent.com/61582763/193343408-6af6b5ce-98a0-4b91-ba8f-c801a2ae1833.jpg)
For example, in the above screenshot, we see an example of an older issue that a contributor is working on

### Additional information

Accidentally opened this Issue on the [wrong repo](https://github.com/EddieHubCommunity/.github/issues/63), sorry about that :sweat

**Comment by Cahllagerfeld** [comment]
Nice find! I have to admit that I actually thought this would be handled [in the current queries](https://github.com/EddieHubCommunity/good-first-issue-finder/blob/7c1443aca6a968f599f8823bbe744c6c9afd5313/src/routes/%2Bpage.ts#L11). They already contain no assignee. Maybe worth investigating in case that's not working.

Do you want to have a look into it?

**Comment by Akshu-on-github** [comment]
My bad, I misunderstood the situation - at a closer glance, the person working on the issue was not assigned to it
Maybe a user guide would be a better fit here?

**Comment by Cahllagerfeld** [comment]
I'm closing this issue for now, as the filtering for non-assigned issues is already in place
