### ISSUE TITLE
Icons in Switcher are not centered

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#247]
### Description

<img width="124" alt="grafik" src="https://user-images.githubusercontent.com/43843195/196220087-a08e6d52-a935-46de-a1d3-a0a508e6e933.png">

The icons in the switcher aren't centered (most obvious the one in the middle). They should  be centered within the button

**Comment by auchynnikau** [comment]
Assign this issue to me.
