### ISSUE TITLE
Search all of github for issue with label "EddieHub:good-first-issue"

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/good-first-issue-finder#25]

**Comment by krshdev** [comment]
Can I work on this?

**Comment by Cahllagerfeld** [comment]
As far as I remember thats a roadmap-feature for the future. In my opnion we should focus on stability and UI for quering just the Org for now. What do you think about it @eddiejaoude ?

**Comment by eddiejaoude** [comment]
You are project lead on this @Cahllagerfeld , I will take your advice on this
