### ISSUE TITLE
[BUG] Missing spaces cause invalid Markdown list

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/good-first-issue-finder#255]
### Description

There are missing spaces in the contributing file which prevents proper Markdown lists/formatting.

https://github.com/EddieHubCommunity/good-first-issue-finder/blob/d80ea8883ae8c85a466da27db58beefe818c8bb1/CONTRIBUTING.md?#L45-L47

### Steps to contribute

_If you've already forked the repository, skip to step 3_

1. Fork the repository [**here**](https://github.com/EddieHubCommunity/good-first-issue-finder/fork).
2. Make a new branch named `fix_markdown`.
3. Open the `CONTRIBUTING.md` file in the root directory.
4. From lines 45-47, replace the current content with the following content.

```markdown
- Add a `.env` file in the root directory of the folder

- Paste the code below inside the `.env` file with your secret token
```

5. Commit and push your changes.
6. Make a [**pull request**](https://github.com/EddieHubCommunity/good-first-issue-finder/compare) in the head repository.
7. You're done now! 🎉 You just have to wait until the maintainers review your pull request.

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by joeshajan** [comment]
Hey @Panquesito7 I'm a beginner and I think I can fix this. Can you assign this to me.
