### ISSUE TITLE
[FEATURE] add loader while data being loaded.

### ISSUE THREAD

**Issue by RakeshSangem** [EddieHubCommunity/good-first-issue-finder#258]
### Description

When user want to switch between `EddieHub` to `GitHub` vise versa there is a delay this can leads bad experience to the user.

We can implement:
- we show simple loader while data being loaded in the background
- In future, we can go with skeletons too.

https://user-images.githubusercontent.com/107752425/208309131-32350ad6-57b4-4b67-8632-7fc474a9ba0b.mp4

**Comment by joeshajan** [comment]
Hey, @RakeshSangem are you working on this issue? if not I would like to take it. Can you assign this to me?

**Comment by Akhil2707** [comment]
hey @RakeshSangem shall I start working on it ?

**Comment by RakeshSangem** [comment]
Hey @joeshajan and @Akhil270! I'm not working on it. So you can ask the maintainers to assign this task to you.

Thank you!
