### ISSUE TITLE
Filter out Archived Repos

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#265]
### Description

Currently issues from archived repos are shown. They should be filtered out

**Comment by Cahllagerfeld** [comment]
@tbhaxor I thought about this, I think it may make sense to do this filtering inside the Github-Query with `archived:false` and not after we fetched the data. What do you think?

**Comment by tbhaxor** [comment]
Still including the archived repos, also the query is now updated to `-is:archived`. Negations in github is done by prepending the `-` sign to the queries.

**Comment by tbhaxor** [comment]
Also this works with `type: REPOSITORY`

**Comment by Cahllagerfeld** [comment]
I was having a look at this doc https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-based-on-whether-a-repository-is-archived
