### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by Hrishi5111998** [EddieHubCommunity/good-first-issue-finder#272]
### Description

here in the Readme file of Good first issue finder by EddieHub there is a word called **"pave",** at first new user finds it difficult to understand its meaning. So I would suggest  for this line **"pave their path"**  we can write **"to make it easier for"**. I hope this makes sense! thank you.

### Screenshots

![2023-01-15](https://user-images.githubusercontent.com/115489262/212541173-9aa82721-ecfc-4c9e-a550-2e285c31bdee.png)

**Comment by AniketNS** [comment]
Hey @Hrishi5111998, I would like to do this. Can u please assign this to me? I'll create a PR as soon as possible.

**Comment by Hrishi5111998** [comment]
> Hey @Hrishi5111998, I would like to do this. Can u please assign this to me? I'll create a PR as soon as possible.

PR already created. Thank you for taking interest.

**Comment by Cahllagerfeld** [comment]
closed with #275
