### ISSUE TITLE
[OTHER] Change the colors of the discord and github icons on hover

### ISSUE THREAD

**Issue by Vishvsalvi** [EddieHubCommunity/good-first-issue-finder#280]
### What would you like to share?

Change the hover color of the discord icon to indigo-500 and lime-500 of github

![image](https://user-images.githubusercontent.com/82429084/214526579-b1defe56-b9db-4007-a801-c64febd1249c.png)

### Additional information

Keep it a good first issue

**Comment by djv03** [comment]
Would love to fix it

**Comment by Subhrajit-Dutta** [comment]
Hey! if no one is working on this issue can you assign it to me? I would love to fix it.

**Comment by Cahllagerfeld** [comment]
Hey, I think @djv03 was first, so I'll assign it to them. Feel free to pick another issue or ask for help 🙏

**Comment by djv03** [comment]
@Vishvsalvi I have fixed the issue but I don't know how to test it!
can you please help me  with this
![eddiehub_issuesolved](https://user-images.githubusercontent.com/93385841/215109584-699e09c8-7d76-41b1-91c5-1a5ddf2ee5d1.png)

**Comment by Vishvsalvi** [comment]
Read the documentation for testing it on your local machine

**Comment by Cahllagerfeld** [comment]
First you need to install the Playwright dependencies with ```npx playwright install --with-deps```.
After that you can run the test script from the `package.json`

**Comment by saaagarsingh** [comment]
Hey @Cahllagerfeld, is this issue resolved???

**Comment by Cahllagerfeld** [comment]
#300 is already opened for it, it should be merged very soon I think

**Comment by djv03** [comment]
apologies for delayed work...getting some issues with my git...get back to
you by tomorrow evening

**Comment by BurakTaner** [comment]
@Cahllagerfeld Looks like Pr is merged but issue didn't close because creator of PR forget to add link to this issue. Can you close as approved?

**Comment by djv03** [comment]
thank you @BurakTaner for pointing this out!
