### ISSUE TITLE
Labels hidden when no results found

### ISSUE THREAD

**Issue by Ananya2001-an** [EddieHubCommunity/good-first-issue-finder#286]
### Description

After clicking some labels if we get no results then the filter labels just disappear making it impossible to revert the changes and search for a different combination. 

### Screenshots

https://user-images.githubusercontent.com/55504616/216354712-5a8421e9-69a8-4c27-b8b1-92c74a49cca7.MOV

**Comment by Ananya2001-an** [comment]
I would like to work on this issue

**Comment by Ananya2001-an** [comment]
I will try once if it doesn't work then you can put it to backlog

**Comment by Ananya2001-an** [comment]
Hey @Cahllagerfeld I just checked recently that the labels are again hiding on no results found. Is that happening because of the different tags getting regenerated every time.

**Comment by Ananya2001-an** [comment]
We have to unnecessarily refresh every time no results are found so as that we can search again.

**Comment by Cahllagerfeld** [comment]
Uhm, I think this is my fault, I refactored the state-management and had to rewrite a few things 😅. If you want, you can fix it again, but I can also do it. Whatever fits for you 👍

**Comment by Ananya2001-an** [comment]
> Uhm, I think this is my fault, I refactored the state-management and had to rewrite a few things 😅. If you want, you can fix it again, but I can also do it. Whatever fits for you 👍

I guess you should do it because I already did it once. It will seem weird to get 2 PR's merged for the same issue.😂
