### ISSUE TITLE
[OTHER] Close Profile Info onNavigation

### ISSUE THREAD

**Issue by Devangyadav26** [EddieHubCommunity/good-first-issue-finder#293]
### What would you like to share?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/104856377/217554098-9e6aae1c-578e-4884-aa6c-830f94bd73fc.png">

The section popped up with my name, doesn't closes **automatically** even on going back to home page or when I click on Docs link.

**Comment by Cahllagerfeld** [comment]
The dialog closes when clicking on your profile picture again.
We should close the modal on navigate though 🤔

**Comment by Devangyadav26** [comment]
Yes Exactly! reducing the clicks for user

**Comment by Cahllagerfeld** [comment]
This issue can be resolved in the following way: 

1. check `$navigating`[[1](https://kit.svelte.dev/docs/modules#$app-stores-navigating)] or use the `beforeNavigate` [[1](https://kit.svelte.dev/docs/modules#$app-navigation-beforenavigate)]
2. update flag for displaying the avatar popup in the layout

**Comment by Cahllagerfeld** [comment]
Did you configure the Github-Auth-App like described in the [Readme](https://github.com/EddieHubCommunity/good-first-issue-finder#%EF%B8%8F-installation-steps)?

**Comment by soumya-ranjan-pratap** [comment]
I want to contribute, can you please assign this to me?

**Comment by Cahllagerfeld** [comment]
Double checking if @Devangyadav26 is working on it already, as he opened the Issue 👍

**Comment by Devangyadav26** [comment]
Hey , working on this issue if I won't make it till end will inform than @soumya-ranjan-pratap  you can go ahead!

**Comment by soumya-ranjan-pratap** [comment]
thank you

**Comment by Devangyadav26** [comment]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/104856377/217734860-db02cd76-9ae2-473f-8364-acab604992aa.png">
While Pushing the changes I am facing this issue.

**Comment by Devangyadav26** [comment]
hey @Cahllagerfeld , was facing some issues and work on this again can u please guide me the changes which you told in PR?

**Comment by Cahllagerfeld** [comment]
The changes suggested in the codeblock
```ts
  beforeNavigate(() => {
    displayPopover = false;
    destroyInstance();
  });
```

are based on the documentation, that are linked in [this comment](https://github.com/EddieHubCommunity/good-first-issue-finder/issues/293#issuecomment-1422681492)

Does this help?

**Comment by Devangyadav26** [comment]
Trying this today, will revert back
