### ISSUE TITLE
[OTHER] Change the color of Docs menu-item on hover

### ISSUE THREAD

**Issue by Purvi-Gupta** [EddieHubCommunity/good-first-issue-finder#311]
### What would you like to share?

Change the color of docs menu-item into primary-300

**Comment by Saikat-Mandal** [comment]
Hello @Purvi-Gupta are you working on this  issue ?

**Comment by saaagarsingh** [comment]
Is there anyone working on this issue coz if not then I would love to work on it.

**Comment by Cahllagerfeld** [comment]
there is #312 open for it already 👍
