### ISSUE TITLE
[FEATURE] Button to go back to app from Docs page

### ISSUE THREAD

**Issue by mrb1nary** [EddieHubCommunity/good-first-issue-finder#313]
### Description

There is no button to close the docs page once it is opened. Clicking on the icon redirects us back to the homepage and not to the app page.

### Screenshots

![image](https://user-images.githubusercontent.com/55779046/222337222-5c14db28-d1b5-49f4-bc7c-d1170d645076.png)

### Additional information

Suggestion: 
Add a cross button to close the docs page

**Comment by saaagarsingh** [comment]
Hey can I work on this issue???

**Comment by Cahllagerfeld** [comment]
As it's a regular route, we cannot just close it. I think we should add a button to the page that links to `/app`. What do you think?

**Comment by harshit-002** [comment]
Heyy, I added a div in the `+layout.svelte` of the docs which links to the homepage, is it fine?  or should i do it some otherway?
<img width="581" alt="image" src="https://user-images.githubusercontent.com/95224348/222979131-168611df-da4b-4de2-9393-e4d3b393bd99.png">

**Comment by harshit-002** [comment]
> Actually the issue was to redirect it back to 'app' page. Clicking on the logo(top left) already does this. Does your 'back to homepage' redirects us to app or homepage?

I changed it, now it redirects to app page (` "/app"` ), should i pull?
<img width="720" alt="image" src="https://user-images.githubusercontent.com/95224348/223086592-c093dc57-b59c-428c-aab3-6b8972a6aacb.png">

**Comment by Cahllagerfeld** [comment]
Hey, @saaagarsingh I want to double check with you before merging as this issue is assigned to you initially.

**Comment by saaagarsingh** [comment]
Yeah @Cahllagerfeld go ahead and merge the solution since we all here are resolve the issues.
