### ISSUE TITLE
[OTHER] Improve animation color of github of techstack in dark mode

### ISSUE THREAD

**Issue by MahirMahdi** [EddieHubCommunity/good-first-issue-finder#315]
### What would you like to share?

It would look better if the animation color is changed from black to white in dark mode.

![Screenshot 2023-03-20 155605](https://user-images.githubusercontent.com/66949598/226305872-5d74d566-f48c-4ccd-ab05-7cedb806f465.png)

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by Cahllagerfeld** [comment]
sure 👍

**Comment by Srinja333** [comment]
@Cahllagerfeld  please check it out

**Comment by Poonam1607** [comment]
It's still showing the black color in dark mode @Srinja333

**Comment by abdullah43577** [comment]
@MahirMahdi  I would like to know if this issue is fixed or if I should work on the fix

**Comment by MahirMahdi** [comment]
> @MahirMahdi I would like to know if this issue is fixed or if I should work on the fix

Ig someone has made a PR on it. But it's not merged yet.

**Comment by abdullah43577** [comment]
> > @MahirMahdi I would like to know if this issue is fixed or if I should work on the fix
> 
> Ig someone has made a PR on it. But it's not merged yet.

ok

**Comment by anubhav1206** [comment]
Can I work on this

**Comment by Cahllagerfeld** [comment]
its opened with #316 alreay 👍

**Comment by Rajeevjewar** [comment]
> ### What would you like to share?
> It would look better if the animation color is changed from black to white in dark mode.
> 
> ![Screenshot 2023-03-20 155605](https://user-images.githubusercontent.com/66949598/226305872-5d74d566-f48c-4ccd-ab05-7cedb806f465.png)
> 
> ### Additional information
> _No response_

Yeah Exactly because It doesn't show a good visual hierarchy it should good idea to change the dark color to light version of its body background color;
we can use try these two colors:
#e9e9ea 
#d3d4d5
both colors are the tint versions of the main color

**Comment by rahul0x00** [comment]
@Cahllagerfeld Hi,is it still open?

**Comment by Cahllagerfeld** [comment]
Yep, as there hasn't been any activity here, I'll assign it to you 👍

**Comment by rahul0x00** [comment]
Should i change the contrast or make it dynamic like white in dark mode and black in light mode,in my opinion the former makes more sense

**Comment by Cahllagerfeld** [comment]
exactly, that's the intended behavior. I think for light mode its fine already, it only requires the adjustment for dark mode 👍

**Comment by rahul0x00** [comment]
Hi, @Cahllagerfeld I've addressed the issue, please take a look at the PR, and let me know if any further modifications or adjustments are required
