### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by dprabhat670** [EddieHubCommunity/good-first-issue-finder#318]
### Description

I am  raising this issue to join the community here !

**Comment by Cahllagerfeld** [comment]
Hey, thanks for your issue. If you want to join the Eddiehub-Community, please open an issue in the [support repo](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization). I'll close this issue, as its not related to this project itself
