### ISSUE TITLE
Deploy to EddieHub's kubernetes cluster

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/good-first-issue-finder#32]
- [x] build + push to GH container registry
- [x] create release
- [x] deploy
- [ ] add `VITE_TOKEN` for GitHub token

**Comment by Cahllagerfeld** [comment]
Awesome, thanks for raising, just a little side-note:
The GH-Token needs to live in the env-variable with the name `VITE_TOKEN` when deploying to the cluster

**Comment by eddiejaoude** [comment]
Ah yes, thank you! Let me add that as a task 👍
