### ISSUE TITLE
[FEATURE] UPDATE FOOTER FOR GOOD-FIRST-ISSUE-FINDER

### ISSUE THREAD

**Issue by nithin999989** [EddieHubCommunity/good-first-issue-finder#320]
## Description

It would be better to add Twitter and Linked in links also 

### Screenshots

![Screenshot (33)](https://user-images.githubusercontent.com/82808965/232426835-b46ab8ad-7e57-40a5-a415-fc4946e8ea83.png)

**Comment by nithin999989** [comment]
I would like to work on this please assign this to me

**Comment by nithin999989** [comment]
@eddiejaoude

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by Cahllagerfeld** [comment]
I'm not sure which Twitter or linkedin should be added here? Should we add your personal ones @eddiejaoude, or should we exclude them as we're not having dedicated EddiehubCommunity Accounts there? 🤔

**Comment by eddiejaoude** [comment]
We only have EddieHub on LinkedIn, so it could be included here if you think it is relevant @Cahllagerfeld ?

**Comment by Cahllagerfeld** [comment]
I wasn't aware there's Eddiehub on LinkedIn. If we're having a presence there we can also include it I think 👍

**Comment by eddiejaoude** [comment]
It is a very new thing, maybe less than 2 weeks

**Comment by nithin999989** [comment]
i found linked in EddieHub i can add it to this can u assign this to me

**Comment by Rajeevjewar** [comment]
I found both the links 
Twitter:- https://twitter.com/eddiejaoude?s=20
LinkedIn:-https://www.linkedin.com/company/eddiehub/
and I am also a beginner in Open source contribution so please assign this issue to me.

**Comment by Cahllagerfeld** [comment]
I assigned this issue yesterday. Give them time to make their contribution. In the meantime you can have a look at the other open issues :)

**Comment by nithin999989** [comment]
Thanks for assigning me @Cahllagerfeld I will do it in a few days

**Comment by nithin999989** [comment]
@Cahllagerfeld
