### ISSUE TITLE
[DOCS] Use newer GitHub Docs link

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/good-first-issue-finder#324]
### Description

In the contributing guidelines file, there's a link to a GitHub Docs article, however, it's using the old format (`help.github.com`, which is now `docs.github.com`). It still redirects you, but it is best to use the latest links, IMO.

_Steps to contribute_

1. Fork the repository [here](https://github.com/EddieHubCommunity/good-first-issue-finder/fork).
2. Create a new branch named `update_github_link`.
3. Head over to the `CONTRIBUTING.md` file.
4. In line 94, update the help link to: `https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request`.
5. Commit and push your changes.
6. Create a [pull request](https://github.com/EddieHubCommunity/good-first-issue-finder/compare) to compare your changes.
7. That's it! You're done now 🎉 You just have to wait until a maintainer reviews your PR.

If you need any help with this, let us know about it. 🙂

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by yoursmanjunad** [comment]
hey, can you provide some additional information? Like what exactly I've to work on

**Comment by Panquesito7** [comment]
> hey, can you provide some additional information? Like what exactly I've to work on

Hey there. There's a link that needs updating in the contributing guidelines file (see all the steps for more information). 🙂
If you're still confused or need any help, let us know about i!

**Comment by yoursmanjunad** [comment]
Hey, thanks for that; I received it! 

While I notice that you have included all of the stages in the file, I propose that you edit it further. Because most of the steps provided here aren't really abundantly clear. If you need it changed, I can do so, and if you like it, you can include the modifications. First, I attempt to resolve the issue raised in this post, namely, updating the link in Docs.

**Comment by Panquesito7** [comment]
Sure, that'd be great, thanks! Feel free to create separate PRs for those. :)

**Comment by yoursmanjunad** [comment]
Sure! I'll be working on it.

**Comment by yoursmanjunad** [comment]
Hey, I updated the CONTRIBUTING.md file by rewriting the guidelines and providing information for contributors in a more clear and more minimal approach. Please provide comments so that I can create any additional add-ons or modifications.

**Comment by shivamsinghydv** [comment]
Done.

**Comment by shivamsinghydv** [comment]
Hey There! This issue can be closed now.

**Comment by Panquesito7** [comment]
> Hey There! This issue can be closed now.

Hmm, it appears you created the PR in your fork and not the original repository. 😅

**Comment by ayesha-firdaus** [comment]
Hii, I am looking  for project to contribute .Can I work on this please assign me

**Comment by ayesha-firdaus** [comment]
this issue is closed?

**Comment by bagoviggo** [comment]
> this issue is closed?

co-asks 👀
