### ISSUE TITLE
[FEATURE] Close the profile info on clicking outside the profile button

### ISSUE THREAD

**Issue by prasarCodes** [EddieHubCommunity/good-first-issue-finder#334]
### Description

Currently, the profile info closes only when the profile picture button is clicked. It would be nice if the profile info can also be closed by clicking outside the button anywhere on the page.

### Screenshots

![image](https://user-images.githubusercontent.com/55887682/236644688-2cc128d0-a7b9-4ec1-a5d2-c91d845c9518.png)

**Comment by Cahllagerfeld** [comment]
Nice idea 👍

**Comment by prasarCodes** [comment]
Please assign this to me when it is ready for dev

**Comment by Gallantfarhan** [comment]
that's a good idea, if nobody is assigned to this I can make the changes.

**Comment by prasarCodes** [comment]
@Gallantfarhan I already changed the code and added a pull request. Waiting for review.
