### ISSUE TITLE
text not visible

### ISSUE THREAD

**Issue by Not-Sarthak** [EddieHubCommunity/good-first-issue-finder#348]
### Description

In the dark mode, the ui text is set to light in the filters section which makes the text unreadable as it matches up with the background color.

### Screenshots

![image](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/92942966/54d37bca-1757-4454-9a87-db3bb77f9656)

**Comment by Cahllagerfeld** [comment]
nice catch! 
I'm closing it as a duplicate of #342
