### ISSUE TITLE
[DOCS] add proper readme

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#35]
The project currently uses the boilerplate-readme. This should be replaced by a Eddiehub-One

**Comment by krshdev** [comment]
I'd love to work on this.

**Comment by KendallDoesCoding** [comment]
#108 is something to consider in the proper README.md @krshdev

**Comment by schmelto** [comment]
@krshdev how is it going?

**Comment by krshdev** [comment]
Hi @schmelto Really sorry I forgot that I was assigned to this issue because of exam rush... I will open a pull request this week and get this done ✅

**Comment by schmelto** [comment]
> Hi @schmelto Really sorry I forgot that I was assigned to this issue because of exam rush... I will open a pull request this week and get this done ✅

Sure no rush
