### ISSUE TITLE
[OTHER] -Review the position and style of the Add Testimonial Bubble

### ISSUE THREAD

**Issue by katzjeff** [EddieHubCommunity/good-first-issue-finder#351]
### What would you like to share?

Hi team,
Am not so sure is this should fall here or under the General feature request, given the limited options of selecting for an update to the feature, but anyway...

**This is just a request to review the positioning or rather the design of the "Add testimonial for..." bubble at the bottom of the page. The current position tends to hide the social media icons, both when in mobile and full screen views. See images below**

![FullScreen](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/31887646/800ff85e-791b-4ecc-b52c-4aa8f1d3a4f8)

Suggestion would be to have just a testimonial icon that's in-line with the other social media icons, thus improving on user experience.

I would like to work on this if approved 

### Additional information

Mobile view of the same issue:
![mobileApp](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/31887646/d2ba9f2f-806c-4048-bbfd-fb93839fdb9c)

**Comment by Cahllagerfeld** [comment]
I think this issue, isn't related to this repo, but for linkfree, isn't it?

In case it is, we could transfer the issue to linkfree, in case it isn't a duplicate @eddiejaoude.

**Comment by katzjeff** [comment]
> I think this issue, isn't related to this repo, but for linkfree, isn't it?
> 
> In case it is, we could transfer the issue to linkfree, in case it isn't a duplicate @eddiejaoude.

@Cahllagerfeld ...thanks for the heads up. My mistake thought i was at the linkfree repo. 
Will transfer the issue there once i confirm it isnt a duplicate
