### ISSUE TITLE
[FEATURE] ONE BUTTON FOR DARK AND LIGHT MODE

### ISSUE THREAD

**Issue by nithin999989** [EddieHubCommunity/good-first-issue-finder#352]
### Description

Instead of having two buttons for switching between dark mode and light mode having one button for both dark mode and light mode same as linkfree website
Now look
![Screenshot (138)](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/82808965/f8653495-8053-45b8-bd05-780e483e9e79)
After only single button (prototype):-
![Screenshot (142)](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/82808965/ecc38d28-1211-4141-8fc5-45cb09c01f89)
![Screenshot (140)](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/82808965/6463e787-a3e7-4652-9bc0-0da5c35cc500)
like this we can just one button to toggle between two dark and light modes

**Comment by Cahllagerfeld** [comment]
How would you use the system theme with this approach?

**Comment by Cahllagerfeld** [comment]
I think it's not implemented there 🤔 😅

**Comment by eddiejaoude** [comment]
Thank you @nithin999989 for the suggestion. But it doesn't need to be the same as LinkFree, so I will close the issue
