### ISSUE TITLE
Leading Empty spaces in query results in empty response in Search

### ISSUE THREAD

**Issue by heysujal** [EddieHubCommunity/good-first-issue-finder#356]
### Description
When a query is entered in the search bar then leading spaces are also being taken into account which results in `Unfortunately, there were no issues found.`

### Screenshots

# Actual Behaviour

Example Search Query(With leading spaces): `      pattern`
Output : 
![image](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/55016909/44d05e77-9a6b-4a01-a8b0-171f0bbe1fed)

Example Search Query(Without any leading space) : `pattern`
Ouput :
![image](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/55016909/f57d9a99-f839-4321-b69f-1ab6f741022e)

### Additional information

On searching for the query `     pattern` search should ignore the leading spaces and should give the same results as `pattern`
This is true for trailing spaces as well. I would like to work on this issue.

**Comment by heysujal** [comment]
\assign

**Comment by Cahllagerfeld** [comment]
Nice catch!

**Comment by saaagarsingh** [comment]
Hey @Cahllagerfeld can I work on this issue?

**Comment by heysujal** [comment]
Hi @Cahllagerfeld i am already working on this issue as i have mentioned in earlier comment
