### ISSUE TITLE
Here is an error page 

### ISSUE THREAD

**Issue by drick-infinity** [EddieHubCommunity/good-first-issue-finder#372]
### Description

There is an code 
<!DOCTYPE html>

   

  <body>
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center row">
                <div class=" col-md-6">
                    <img src="https://cdn.pixabay.com/photo/2017/03/09/12/31/error-2129569__340.jpg" alt=""
                        class="img-fluid">
                </div>
                <div class=" col-md-6 mt-5">
                    <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
                    <p class="lead">
                        The page you’re looking for doesn’t exist.
                    </p>
                    <a href="index.html" class="btn btn-primary">Go Home</a>
                </div>

            </div>
        </div>
    </body>

</html>

### Screenshots

![error page](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/116994649/bab6394e-ebcc-41fd-bdc3-3635e0c27203)

### Additional information

I created the custom error page

**Comment by drick-infinity** [comment]
creating an error page

**Comment by iamYashSinha** [comment]
What will be the requirement?

**Comment by Cahllagerfeld** [comment]
I think the implementation of a custom error page was done with #299.
