### ISSUE TITLE
Hamburger menu hidden in small devices 

### ISSUE THREAD

**Issue by love-sonkar** [EddieHubCommunity/good-first-issue-finder#373]
### Description

Hamburger menu not showing in small devices 

when you check website in small devices or in phone the hamburger is not visible

Expected behavior is hamburger should be visible in small devices

### Screenshots

![header](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/82786865/bd2dbc15-d250-41e1-bcf6-1245aff16658)
![chrome_NKkiwPjvl8](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/82786865/cff46be6-ee37-4823-8825-781c1c56e71a)

**Comment by shivang17d** [comment]
Can I work on it ??

**Comment by love-sonkar** [comment]
i already fixed bro 😀 you can check another issue
