### ISSUE TITLE
setting icon/button not working

### ISSUE THREAD

**Issue by Bhavik-prajapati** [EddieHubCommunity/good-first-issue-finder#375]
### Description

![image](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/109121443/1fca1321-d2c3-46cf-9b8f-b63765df1dbf)
setting button is not working

### Screenshots

![image](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/109121443/6e19d50d-7b91-4d83-badb-f1792d671bcc)

**Comment by iamYashSinha** [comment]
On which page you're getting this issue? Please try to provide the proper details.

**Comment by Abhish7k** [comment]
That is actually for the theme and the settings icon is for the system default theme while other two are for light and dark mode.

**Comment by iamYashSinha** [comment]
Nothing needs to be fixed here right?

**Comment by Bhavik-prajapati** [comment]
oh my bad sorry
