### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by Chanchal-D** [EddieHubCommunity/good-first-issue-finder#376]
### Description

update readme file

**Comment by Cahllagerfeld** [comment]
Can you please be more descriptive, what and why we should update the readme?:

Please also add a descriptive title to your issue

**Comment by iemafzalhassan** [comment]
can i work on this issue. ?

**Comment by Cahllagerfeld** [comment]
I'll close this issue, as it's not clear what the intention is, and also due to inactivity. Feel free to pick another issue @iemafzalhassan 👍

**Comment by iemafzalhassan** [comment]
Okey @Cahllagerfeld . Thanks a lot for replying.😊
