### ISSUE TITLE
[Improvement] Consolidate build and test in one GitHub Action

### ISSUE THREAD

**Issue by tbhaxor** [EddieHubCommunity/good-first-issue-finder#383]
### What would you like to share?

Currently there are two separate actions **build** and **test** both of them doing same thing to build it first.

I propose to have a unit test steps like this

1. Configure environment
2. Install nodejs and npm packages
3. Build the code
4. Install playwright dependencies
5. Run testing

If it would fail at step 3, it wont go onto further steps. This will save build times and resources.

**Comment by Cahllagerfeld** [comment]
sounds good to me 👍

**Comment by tbhaxor** [comment]
Its implemented @Cahllagerfeld
