### ISSUE TITLE
[OTHER] I want to add my own project 

### ISSUE THREAD

**Issue by Akshat111111** [EddieHubCommunity/good-first-issue-finder#397]
### What would you like to share?

Thankyou so much for making such a awesome application.i want to add my own project too in the list.How can i do it so??

**Comment by Cahllagerfeld** [comment]
You need to label issues in your project with a label, like described [in the docs](https://finder.eddiehub.io/docs/your-issues). I hope this answers your question :). Let me know if you need further help
