### ISSUE TITLE
Th error gif one the api error is not found

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/good-first-issue-finder#401]
### Description

Hello:)
While browsing on the good first issue finder I went to the api page, and I found that the gif is not found

### Screenshots

![image](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/110662505/c67f631c-0874-4eb4-be5c-c696501e3b1e)

### Additional information

I would love to work on this

**Comment by Bashamega** [comment]
Should I work on it @eddiejaoude

**Comment by eddiejaoude** [comment]
Thanks for raising the issue @Bashamega 

Let me tag @Cahllagerfeld

**Comment by Bashamega** [comment]
> Thanks for raising the issue @Bashamega
> 
> Let me tag @Cahllagerfeld

ok

**Comment by nithin999989** [comment]
please assign this to me

**Comment by nithin999989** [comment]
@eddiejaoude @Cahllagerfeld

**Comment by eddiejaoude** [comment]
sorry for the delay, I missed this notification.

@Bashamega would you still like to work on the issue, if not I can pass it on to someone else?

**Comment by Bashamega** [comment]
> sorry for the delay, I missed this notification.
> 
> @Bashamega would you still like to work on the issue, if not I can pass it on to someone else?

No problem, I would love that

**Comment by eddiejaoude** [comment]
Great, I have assigned it to you

**Comment by Bashamega** [comment]
> Great, I have assigned it to you @Bashamega

Thanks
