### ISSUE TITLE
add label action

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#47]
Add [this](https://github.com/EddieHubCommunity/api/blob/main/.github/workflows/labels.yml) action to the repo

**Comment by Siddhant-K-code** [comment]
is this issue for PR/Issue automated labelling?

**Comment by Cahllagerfeld** [comment]
I think the title of the issue isnt that good, I need to update the description as well, let me try to clarify it: 
We're having a Action that generates lables, that can be added to the issues. Because of that we have the same labels in every Org-Repo which makes it easier for quering labels throughout the org.

**Comment by Siddhant-K-code** [comment]
we can add good first issue label to this, so that a beginner can take this up :)

**Comment by FahimFBA** [comment]
Can I work on this?

**Comment by FahimFBA** [comment]
Can I work on this?

**Comment by Cahllagerfeld** [comment]
Sure

**Comment by FahimFBA** [comment]
I have added the PR.

**Comment by Cahllagerfeld** [comment]
closed with #50
