### ISSUE TITLE
[FEATURE] Update favicon file format

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#60]
### Description

Update "favicon.png" to "favicon.ico"

I would love to work on this, please assign me.

**Comment by Cahllagerfeld** [comment]
I think this can be tackled together with #43

**Comment by KendallDoesCoding** [comment]
> I think this can be tackled together with #43

Yeah, thought the same thing but for now, till we update the favicon, it would be nice if its .ico.

**Comment by susheelpal** [comment]
is it done? I would like to contribute. I am a newbie here.

**Comment by KendallDoesCoding** [comment]
I made a pr and it got little messed up but then I've been busy with
personal projects so ig you can be assigned on this.

**Comment by Cahllagerfeld** [comment]
Okay, thanks for that info @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
:D

**Comment by KendallDoesCoding** [comment]
@susheelpal Although, if you need any help, I'll try my best... After creating this issue, recently, I've setup Git so I can run and fix the issue on localhost :D

**Comment by susheelpal** [comment]
git push -u origin susheel
remote: Permission to EddieHubCommunity/good-first-issue-finder.git denied to susheelpal.
fatal: unable to access 'https://github.com/EddieHubCommunity/good-first-issue-finder.git/': The requested URL returned error: 403

I am getting this issue. I am not able to get why it is happening.

**Comment by Cahllagerfeld** [comment]
You need to fork the repo first.

**Comment by KendallDoesCoding** [comment]
Yup coz you don't have access to this repo as a collaborator, so fork the repo and clone the fork. If you need help, please let me know.

**Comment by susheelpal** [comment]
yes, it was a fork issue. thank you so much for guiding me

**Comment by KendallDoesCoding** [comment]
Any update on this @susheelpal ?

**Comment by susheelpal** [comment]
I am not able to run in my local even after adding "start" in package.json
![favicon](https://user-images.githubusercontent.com/57487901/156627463-e73369cb-1539-4572-9f50-6feadaba0182.jpg)

**Comment by chiraglal** [comment]
Can i work on this issue?

**Comment by Cahllagerfeld** [comment]
@susheelpal are you still on this?

**Comment by Dharmik48** [comment]
As I am working on issue #43 I will fix this one too as both are related
