### ISSUE TITLE
[OTHER] The issue template is coded via Node?

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#61]
### What would you like to share?

Is the issue template coded via Node?

**Comment by Cahllagerfeld** [comment]
The Labels are defined [here](https://github.com/EddieHubCommunity/.github/tree/main/.github/ISSUE_TEMPLATE)

**Comment by KendallDoesCoding** [comment]
> The Labels are defined [here](https://github.com/EddieHubCommunity/.github/tree/main/.github/ISSUE_TEMPLATE)

Then why don't the labels defined work? #62

**Comment by Cahllagerfeld** [comment]
I think the labels defined in the templates aren't available in the repo. We are using standard-labels across all Eddiehub-projects, thats probably the issue 🤔

**Comment by KendallDoesCoding** [comment]
> I think the labels defined in the templates aren't available in the repo. We are using standard-labels across all Eddiehub-projects, thats probably the issue 🤔

Oh ok.

**Comment by KendallDoesCoding** [comment]
Query Resolved... Closing
