### ISSUE TITLE
[OTHER] Use Shields.io

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#76]
### What would you like to share?

Should we use shields.io in the readme?

**Comment by krshdev** [comment]
yes

**Comment by krshdev** [comment]
eddie said in stream to use

**Comment by Nymphalys** [comment]
Hi,I am interested to work on this issue,I think I can fix this

**Comment by Cahllagerfeld** [comment]
I think we need to discuss first which shields we are actually want to use. 
I'd be in favor of ones indicating the status of the actions though.

Do you have any further ideas @schmelto @eddiejaoude

**Comment by akash19coder** [comment]
@Cahllagerfeld I would like to work on this issue. Would you please assign it to me?

**Comment by Cahllagerfeld** [comment]
closed with #260
