### ISSUE TITLE
please create contributing.md

### ISSUE THREAD

**Issue by susheelpal** [EddieHubCommunity/good-first-issue-finder#79]
### Description

It would be nice if there is the instruction given to run the project.

**Comment by KendallDoesCoding** [comment]
I can work on this.

**Comment by Susmita-Dey** [comment]
> I can work on this.

Okay, then I'm assigning it you.

**Comment by KendallDoesCoding** [comment]
@Susmita-Dey You can't assign me, your not a maintainer, unfortunately :(

**Comment by KendallDoesCoding** [comment]
> > @Susmita-Dey You can't assign me, your not a maintainer, unfortunately :(
> 
> Yes, my bad.

No issues :)

**Comment by shambashib20** [comment]
I can work on this issue. Is there any template or guide to build the CONTRIBUTING.md?

**Comment by alokVerma749** [comment]
I want to fix this issue
