### ISSUE TITLE
[FEATURE] Add badges to README.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#80]
### Description

Add a couple of badges to README.md, for ex: size, closed pr's, closed issues.

**Comment by KendallDoesCoding** [comment]
Please assign this to me.

**Comment by schmelto** [comment]
I'm not sure weather we need closed PRs and closed Issues badge du I not see any value in knowing how many PRs got closed etc.

**Comment by KendallDoesCoding** [comment]
> I'm not sure weather we need closed PRs and closed Issues badge du I not see any value in knowing how many PRs got closed etc.

True, maybe just add a LICENSE badge or something in that case?

**Comment by alokVerma749** [comment]
> > I'm not sure weather we need closed PRs and closed Issues badge du I not see any value in knowing how many PRs got closed etc.
> 
> True, maybe just add a LICENSE badge or something in that case?

yes, the LICENCE badge should be fine.

**Comment by alokVerma749** [comment]
Discord and website badge will be good

**Comment by Kartik2220** [comment]
> I'm not sure weather we need closed PRs and closed Issues badge du I not see any value in knowing how many PRs got closed etc.

added license badge
#172

**Comment by Nymphalys** [comment]
Hi I can work on this issue,can you assign this to me?

**Comment by Fyffeba** [comment]
would be more than happy to assist and help out with this thank you!
