### ISSUE TITLE
[FEATURE] Add labels to issue templates

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#81]
### Description

For feature request, the label to be added automatically should be - [⭐ goal: addition](https://github.com/EddieHubCommunity/good-first-issue-finder/labels/%E2%AD%90%20goal%3A%20addition)
For bug, automatically add the bug label.
For docs, automatically add the documentation label.

### Additional information

I can work on this issue.

**Comment by schmelto** [comment]
You could take a look here if

https://github.com/EddieHubCommunity/support/blob/main/.github/ISSUE_TEMPLATE/bug.yml

**Comment by siddhipatel184** [comment]
I am a beginner and I would like to contribute, however, I am still unsure of how to start about it.

**Comment by MrKrishnaAgarwal** [comment]
I want to work on this issue, please assign to me @schmelto

**Comment by MrKrishnaAgarwal** [comment]
But in which repo, do I have to make the contributions. 
@schmelto

**Comment by MrKrishnaAgarwal** [comment]
Hey @schmelto 
But there is no `.github/ISSUE_TEMPLATE` folder so how can I make the changes?

**Comment by ChinmayMhatre** [comment]
Hey @schmelto, If no one is working on this. I could complete this.

**Comment by shreyashidabral** [comment]
Hii @schmelto, I would like to work on this issue. Can you please assign it to me?

**Comment by Fyffeba** [comment]
Looking to take a crack at this also if its possible!

**Comment by kselena** [comment]
@eddiejaoude This issue was opened up a while ago and I'd like to pick it up.  Other people have asked, but there hasn't been any response.  Can you please assign this to me?

**Comment by eddiejaoude** [comment]
Sure, assigned @kselena

**Comment by kselena** [comment]
@eddiejaoude I was doing some investigation on this issue and found that the issue description is different than what I am seeing.

First issue I came across was that the ***bug*** and ***documentation*** templates already have labels set up and exist in the repo. It doesn't look like either of those templates need to be changed.  The bug template has a https://github.com/EddieHubCommunity/good-first-issue-finder/labels/%F0%9F%9B%A0%20goal%3A%20fix label and documentation has a https://github.com/EddieHubCommunity/good-first-issue-finder/labels/documentation label. 

I looked in the LinkFree repo to compare those labels with what is being requested in this issue and the LinkFree documentation issue template uses the https://github.com/EddieHubCommunity/good-first-issue-finder/labels/%F0%9F%93%84%20aspect%3A%20text label.  

Is the intent to have all of the repos in the organization use the issue templates from the ***organization's .github repo***?   I checked out the ***.github repo*** for the organziation and the issue templates are slightly different than the repo level issue templates.  Should the organization templates be modified for all of the repos in the organization and the issue templates deleted from each repo?  That way, the organization manages the templates for each repo and there is one source of truth.  Calvin does this for his organization and it works out really well. 

---

Here are the templates for you to view:

**Organizational Templates:**
- [Feature Request](https://github.com/EddieHubCommunity/.github/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml)
- [Bug](https://github.com/EddieHubCommunity/.github/blob/main/.github/ISSUE_TEMPLATE/bug.yml)
- [Documentation](https://github.com/EddieHubCommunity/.github/blob/main/.github/ISSUE_TEMPLATE/docs.yml)


**Link Free Templates:**
- [Feature Request](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml)
- [Bug](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/ISSUE_TEMPLATE/bug.yml)
- [Documentation](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/ISSUE_TEMPLATE/docs.yml)

**Comment by eddiejaoude** [comment]
> Is the intent to have all of the repos in the organization use the issue templates from the organization's .github repo? I checked out the .github repo for the organziation and the issue templates are slightly different than the repo level issue templates. Should the organization templates be modified for all of the repos in the organization and the issue templates deleted from each repo? That way, the organization manages the templates for each repo and there is one source of truth. Calvin does this for his organization and it works out really well.

oh good spot 👍 yes I think all the repos should have the same templates from the organisation 👍  some repos like LinkFree may have additional templates but the base ones like documentation, bug, feature etc should all come from the Org 💯  - that way we can continually improve them in once place and all repos benefit (plus it is consistent which I really like)

**Comment by kselena** [comment]
@eddiejaoude  I did some research on all of your repos and came up with 7 different categories. Each category lists the name of the repo and numbered under the repo(s), I added the name(s) of the issue template file names they have in common.  As you can see, there are a handful of outliers that have nothing in common with any other repo.  I have not checked to see whether or not any of the templates match each other.  For example, I don't know if all the bug templates have the same information in them.  I also noticed that there is a **_feature_request_** template and a **_feature_** template.  

Calvin did some testing and he said that if the repo has a .github folder with an issue template in it, the repo will use its own template and not the organization's template. He also said that you can't mix and match files.  For example, if you want to have bug, docs and feature templates at the organization level, but you want an extra testimonial template in the **LinkFree** repo, that repo will not use the organizational templates.

Basically, if you want to be consistent in any of your templates, you either need to have them all at the organizational level or at the repo level.  If they're at the repo level, they will need to be maintained separately and you'll need to trust that they match.  In essence, they're duplicate files.  If you change an org template, you will need to update that same template at the repo level.

At this point, you will need to make a decision on what the organizational templates will be and whether or not you want to manage templates in each or certain repos. 

If you want to make sure we're on the same page, we're happy to have a call on Discord.  

#### These repos have the same issue templates:
 - good-first-issue-finder**
 - .github
 - EddieHubCommunity.github.io
1. bug, config, docs, feature_request, other

#### These repos have the same issue templates:
 - infrastructure
 - gh-action-open-source-labels
	1. bug, feature_request, other


#### OUTLIERS
  - support
	1. add-api-user, bug, config, delete-api-user, gh-profile-review, github-sponsors-profile-review, ideas, invitation, opensource-review, other, portfolio-review, resume-review, twitter-review
  - Branding
	1. feature
 - awesome-github-profiles
	1. add-an-awesome-github-profile
  - EddieBot(Files)
	1. bug, config, docs, ideas, other
 - api
	1. bug, config, feature, other
 - LinkFree
	1. Bug, config, docs, feature_request, other, testimonial
 - hacktoberfest-practice
	1. bug_report, config, docs, feature, other
 - monitoring
	1. bug_report, config


#### NO ISSUE TEMPLATES
- template
- gh-actions-html-table-generator
- gh-action-community
- EddieBotBreakout
- EddieHubLive

#### ARCHIVED, NO ISSUE TEMPLATES
- EddieHubCommunity.github.io
- transcriptions (archived)
- Hackathons (archived)

#### ARCHIVED, NO .GITHUB FOLDER
LiveStream_GitOps_Demo (archived)
DailyTips (archived)

#### ARCHIVED, ISSUE TEMPLATES
- EventCalendar (archived)
	1. bug_report, config, feature_request, other
- EdditBotUI (archived)
	1. bug_report, custom, feature_request

**Comment by Cahllagerfeld** [comment]
Maybe we should move this org-wide discussion to a [discussion in the support repo](https://github.com/EddieHubCommunity/support/discussions)

**Comment by kselena** [comment]
@Cahllagerfeld discussion created https://github.com/EddieHubCommunity/support/discussions/6401

**Comment by eddiejaoude** [comment]
> OUTLIERS

That made me laugh

Thank you both! Yes I think this is bigger than this specific repo, Org discussion makes sense 👍 

I will close this and let's continue in the new Org discussion - we can then create specific issues on each repo if/when required
