### ISSUE TITLE
[FEATURE] Dynamic Image On Issue

### ISSUE THREAD

**Issue by krshkodes** [EddieHubCommunity/good-first-issue-finder#82]
### Description

![image](https://user-images.githubusercontent.com/91655303/155998082-07184e2e-17da-4a2d-b918-a7fa24363aad.png)

Currently, it is just github logo, could be

- the pfp of the issue author
- pfp of the repo owner

**Comment by Cahllagerfeld** [comment]
I'm not sure about that, it's probably worth spiking this. The concern I'm having is that it might look a bit odd when having many different icons there. I'm not sure if something more consistent, like the solution we're currently having looks better and feels better UX-wise. If you want to go ahead feel free to work on this though, we'll see how it looks, once you finished it :)

**Comment by Dharmik48** [comment]
Okay then, I make the changes and raise a PR, then you can see if it looks better or not then decide to keep it or note

**Comment by Cahllagerfeld** [comment]
I'd love to collaborate and get your take on it too :D I always try to avoid making decisions based on my own opinions :D You'll get the best results possible if you also hear and respect other opinions :D

**Comment by Dharmik48** [comment]
> I'd love to collaborate and get your take on it too :D I always try to avoid making decisions based on my own opinions :D You'll get the best results possible if you also hear and respect other opinions :D

That is a very good mindset you have there

**Comment by Dharmik48** [comment]
It is indeed true that we can get better results by listening and respect other's thoughts

**Comment by Dharmik48** [comment]
It will look something like this
![image](https://user-images.githubusercontent.com/64529217/177010549-ff2cf9f1-0720-4f03-b268-6889769bb316.png)
