### ISSUE TITLE
[DOCS] CODE OF CONDUCT

### ISSUE THREAD

**Issue by Susmita-Dey** [EddieHubCommunity/good-first-issue-finder#84]
### Description

Kindly create a CODE_OF_CONDUCT.md file in this repo. CODE_OF_CONDUCT is missing here.
I'll be happy if I'm assigned to do so.

**Comment by Susmita-Dey** [comment]
Hey, there are **2 types of code of conduct**. I usually use the first one for my repos. 

**Shall I add the first one here or the second one?**

![image](https://user-images.githubusercontent.com/79099734/155999254-53645595-0768-492b-a129-096a871cbdc6.png)

**Comment by schmelto** [comment]
> Hey, there are **2 types of code of conduct**. I usually use the first one for my repos.
> 
> **Shall I add the first one here or the second one?**
> 
> ![image](https://user-images.githubusercontent.com/79099734/155999254-53645595-0768-492b-a129-096a871cbdc6.png)

I would suggest taking a look at the other EddieHub repos. :D

**Comment by Susmita-Dey** [comment]
Okay, thanks

**Comment by schmelto** [comment]
https://github.com/EddieHubCommunity/support/blob/main/CODE_OF_CONDUCT.md
