### ISSUE TITLE
Make text in footer, just icons

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#86]
### Description

Make text "Discord", "Github" with hyperlinks in footer, icons using font awesome.

### Additional information

I may be able to work on this.

**Comment by emmalearnscode** [comment]
If this is done, make sure the icons have aria labels so that they are still accessible.

**Comment by DurveshKumarPal** [comment]
@emmalearnscode can I work on this issue??

**Comment by DurveshKumarPal** [comment]
@emmalearnscode  I'm unable to figure out to install setup can you plz Guide

**Comment by emmalearnscode** [comment]
Which stage are you getting stuck on? @DurveshKumarPal

**Comment by emmalearnscode** [comment]
Instruction 3 is currently wrong and someone is working on it but it should say cd good-first-issue-finder instead of cd linkfree

**Comment by chiraglal** [comment]
Is this issue solved yet?, I can help add the icons instead of the text.

**Comment by emmalearnscode** [comment]
@chiraglal No it's not solved yet, please go ahead.

**Comment by gandhiv88** [comment]
If the issue is not yet resolved, I would like to work on it.

**Comment by Cahllagerfeld** [comment]
closed with #130
