### ISSUE TITLE
[FEATURE] Version number

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#94]
### Description

Add github release version number on the website.

### Additional information

Suggested by Eddie in live-stream, creating a issue incase we forget about it :)

**Comment by aroramrinaal** [comment]
Hey @schmelto, I would like to work on this issue.

**Comment by aroramrinaal** [comment]
> ### Description
> Add github release version number on the website.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> Suggested by Eddie in live-stream, creating a issue incase we forget about it :)

Could you please elaborate the issue. @KendallDoesCoding

**Comment by aroramrinaal** [comment]
Could you please elaborate the issue. @schmelto

**Comment by schmelto** [comment]
> Could you please elaborate the issue. @schmelto 

Adding the current release information to the website like it's done on our linkfree project

**Comment by ianujvarshney** [comment]
could you please assign me the issue. by the way where you need on which as website section this changes. then i ll change that.

**Comment by aroramrinaal** [comment]
> could you please assign me the issue. by the way where you need on which as website section this changes. then i ll change that.

I am working on this.

**Comment by ianujvarshney** [comment]
Ok keep it up. I will resolve others issues.

**Comment by nitishmalang** [comment]
hello Can I work on this issue

**Comment by Cahllagerfeld** [comment]
I think @aroramrinaal is currently working on this issue, please correct me if I am wrong :)

**Comment by eddiejaoude** [comment]
It would be great to get this ticket moving, @aroramrinaal , do you need any help with it or shall we pass it on to someone else?

**Comment by aroramrinaal** [comment]
> It would be great to get this ticket moving, @aroramrinaal , do you need any help with it or shall we pass it on to someone else?

@eddiejaoude , please pass it to someone else.
