### ISSUE TITLE
[FEATURE] Filter by type of issue

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/good-first-issue-finder#97]
### Description

Filter by docs, bug, enhancement... It will be very useful for people who want to fix a certain type of issue, for eg: docs is pretty easy to do so if your a beginner maybe you want to get on the docs stuff instead of bugs and features?

**Comment by Dharmik48** [comment]
Isn't this feature already in the website?
![image](https://user-images.githubusercontent.com/64529217/178108671-4b070bcc-2a52-45fb-afd5-c043f2ec9aed.png)

**Comment by Cahllagerfeld** [comment]
Yes, I think 🤔 closing it for now
