### ISSUE TITLE
[OTHER] change label names

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/good-first-issue-finder#99]
### What would you like to share?

The current toggle label names don’t really express what they are toggling between. To me, global doesn’t convey that I’m searching all of GitHub. I wonder if instead of organisation / global it would be clearer if it stood EddieHub / GitHub. What do you think?

![AE81E08C-841B-4A5B-871C-43139B5CC051](https://user-images.githubusercontent.com/57045550/156215688-aead881e-742d-4ae4-aa06-594fa977a67f.jpeg)

**Comment by KendallDoesCoding** [comment]
Yep, good idea!

**Comment by pathakkar01** [comment]
Hello @emmalearnscode , I would like to work on this issue, If you can Assign me ?

**Comment by pathakkar01** [comment]
Hello @emmalearnscode, I have changed the labels and made a pull request, If you find it correct please merge it the main branch
